### ISSUE TITLE
android:extractNativeLibs="true" for Dynamic Feature Module

### ISSUE THREAD

**Issue by canewsin** [google/bundletool#155] opened 2020-04-14 12:01 UTC
> bundle-tool version 0.9.0

Currently I have some precompiled libs in main/jniLibs/arch/*.so and specifying 

> android:extractNativeLibs="true"

in AndroidManifest.xml to extract them on install,
now i want to move those libs to Dynamic Feature Module.
where i specified bundle manifest as below
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:dist="http://schemas.android.com/apk/distribution"
    package="in.canews.nativelibs">

    <dist:module
        dist:instant="false"
        dist:title="@string/title_nativelibs">
        <dist:delivery>
            <dist:on-demand />
        </dist:delivery>
        <dist:fusing dist:include="true" />
    </dist:module>
    <application android:extractNativeLibs="true"/>
</manifest>
```
but on install of that feature libs are not extracted to libs folder of app.

**Comment by plecesne** [comment] 2020-04-14 16:32
The value of `android:extractNativeLibs` is set by Bundletool and can vary per device, which is why it is ignored in the AAB.

Instead, if you want to disable this optimization, you can set `android.bundle.enableUncompressedNativeLibs=false` in the Gradle properties.

If you don't mind sharing, why do you need to disable this optimization?

**Comment by canewsin** [comment] 2020-04-15 00:54
Already using Gradle properties but no use, I already mentioned the use case, I had precompiled binaries previously I placed them on app/main/jniLibs folder, but now I want them as dynamic feature module, where I want to put them on feature/main/jniLibs. Main benifit I was expecting is when libs are extracted, I will uninstall dynamic module which removes split apk and expecting extracted libs are remained on phone, useful to reduce app update size, if dynamic module is installed, even though content not changed they are updated as usual, but if you uninstall dynamic module only installed one are updated.

**Comment by plecesne** [comment] 2020-04-15 08:44
That seems to be working as intended.

If the native libraries belong to the dynamic feature and the dynamic feature is uninstalled, it is expected for the native libraries to be removed as well. The uninstallation is always deferred so it's possible that the extracted native libraries remain a bit longer in the local storage, but they effectively should not be used.

**Comment by canewsin** [comment] 2020-04-15 10:47
@plecesne native libs are not extracted as intended, after installing dynamic module, I just said the use case on above comment, in real implementation I don't uninstall them as said above. Reopen the issue, since problem is still exists.

**Comment by plecesne** [comment] 2020-04-15 11:00
Ah, I see what you mean now.

The APKs are not installed by the platform immediately which probably explains why you don't see the native libraries. Their presence is instead emulated by SplitCompat.

You didn't answer my question though: why do you need the libraries to be extracted? Could you instead use standard Android APIs to load the libraries, e.g. `System.loadLibrary()` or `dlopen("/path/to/MyApp.apk!libfoo.so", ...)`?

**Comment by canewsin** [comment] 2020-04-15 11:54
I use flutter to build apps,
I use flutter specific apis to run .so file.
these requires furthur .so libs to run, which exists on app home directory
java System.loadLibrary() doesn't have LD_LIBRARY_PATH to specify look up path,
and c stuff, I don't have experience in that.

One thing i noted is 
> <dist:install-time />

if dynamic module is specified as install time module, it is extracting libs, but not for on-demand modules.

**Comment by canewsin** [comment] 2020-04-15 11:55
> The APKs are not installed by the platform immediately which probably explains why you don't see the native libraries. Their presence is instead emulated by SplitCompat.

I was installing as on-demand modules, after installing, system need to extract libs but here it doesn't.

**Comment by plecesne** [comment] 2020-04-15 15:59
You are not actually _installing_ them, you are effectively _requesting the installation_ via the Play Core API, which emulates the installation until it can install it properly at a later time (usually overnight). This happens because an installation would otherwise require the restart of the application.

`System.loadLibrary()` should work for most use-cases, so I'll try to find a relevant point of contact to investigate this. The more information you can provide on the issue with LD_LIBRARY_PATH the better.

**Comment by canewsin** [comment] 2020-04-16 14:38
I'm providing shared libs in assets and extracting them to home directory, currently I seperated those assets as dynamic feature module, download on demand, since home dir is not default on LD_LIBRARY_PATH, so I have to provide in code.

**Comment by plecesne** [comment] 2020-04-16 14:46
Looks similar to https://issuetracker.google.com/issues/147972074#comment13

**Comment by ymakhno** [comment] 2020-04-28 11:12
On-demand feature modules are extracted into `splitcompat` directory inside data application folder. It should be something like this: `/data/data/<package-name>/files/splitcompat`. But I agree that you should not worry about where it is extracted and use `System.loadLibrary`. Could you please share exact problem you have and steps how to reproduce it? Closing for now.

**Closed by ymakhno** 2020-04-28 11:12 UTC

**Comment by canewsin** [comment] 2020-04-28 16:19
Is splitcompat dir has exec permissions targetting Api 29(Android 10) ?

**Comment by ymakhno** [comment] 2020-04-28 18:14
I believe it has such permission for application user.

**Comment by eakteam** [comment] 2022-02-07 01:45
> Is splitcompat dir has exec permissions targetting Api 29(Android 10) ?

It doesn't have exec permissions...

**Comment by eakteam** [comment] 2022-02-07 01:46
> > Is splitcompat dir has exec permissions targetting Api 29(Android 10) ?
> 
> It doesn't have exec permissions...
