### ISSUE TITLE
Integrate bundletool to adb command

### ISSUE THREAD

**Issue by riyaz** [google/bundletool#23] opened 2018-07-19 07:04 UTC
To make it simpler to install app from aab binary, it would be nice if bundletool can be part of android's adb command line, this will be mostly useful for non-devs like testing team they all have adb installed already.

As of now we need another tool to install in all the machines who needs to install app from aab, isn't better if adb natively support to install from aab format and also uses android debug certificate for signing.

as of now i'm using[ this wrapper script.](https://gist.github.com/riyaz/b97d3a80858abd5c0f34a4ce1104ad3d)

**Comment by keyboardsurfer** [comment] 2018-08-01 10:26
Duplicate of #22

**Closed by keyboardsurfer** 2018-08-01 10:26 UTC
