### ISSUE TITLE
Crash installing APKs on API 15-18 emulators

### ISSUE THREAD

**Issue by sampalmer** [google/bundletool#79] opened 2019-06-08 04:21 UTC
**Describe the bug**
Crash installing APKs on API 15-18 emulators

**Bundletool version(s) affected**
Version: 0.9.0

**Stacktrace**

    C:\Utilities\bundletool>java -jar bundletool-all-0.9.0.jar install-apks --apks=app.apks
    The APKs have been extracted in the directory: C:\Users\sam__\AppData\Local\Temp\762967780459134954
    [BT:0.9.0] Error: null
    java.lang.NullPointerException
            at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
            at com.google.common.base.Joiner.toString(Joiner.java:454)
            at com.google.common.base.Joiner.appendTo(Joiner.java:106)
            at com.google.common.base.Joiner.appendTo(Joiner.java:154)
            at com.google.common.base.Joiner.join(Joiner.java:197)
            at com.google.common.base.Joiner.join(Joiner.java:187)
            at com.google.common.base.Joiner.join(Joiner.java:205)
            at com.android.ddmlib.Device.installRemotePackage(Device.java:1024)
            at com.android.ddmlib.Device.installPackage(Device.java:902)
            at com.android.ddmlib.Device.installPackage(Device.java:880)
            at com.android.ddmlib.Device.installPackage(Device.java:869)
            at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:113)
            at com.android.tools.build.bundletool.device.ApksInstaller.installOnDevice(ApksInstaller.java:94)
            at com.android.tools.build.bundletool.device.ApksInstaller.installApks(ApksInstaller.java:82)
            at com.android.tools.build.bundletool.device.ApksInstaller.installApks(ApksInstaller.java:44)
            at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:165)
            at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:88)
            at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)

**To Reproduce**
1. Ensure no physical devices are connected to the computer
1. Launch the API 15, API 16, API 17 or API 18 Android emulator
1. (Due to an unrelated bug, if the emulator screen stays black then you may need to open the emulator's `config.ini` and switch on both `hw.gpu.enabled` and `hw.gpu.mode`)
1. Run `java -jar bundletool-all-0.9.0.jar  build-apks --bundle=app.aab --output=apps.apks`
1. Run `java -jar bundletool-all-0.9.0.jar install-apks --apks=app.apks`

See [artifacts.zip](https://github.com/google/bundletool/files/3268070/artifacts.zip)

**Expected behavior**
App should be installed on the emulator

**Known workaround**
Use the API 29 emulator

**Comment by plecesne** [comment] 2019-06-10 08:41
Dupe of #49.

**Closed by plecesne** 2019-06-10 08:41 UTC
