### ISSUE TITLE
NPE while attempting to install APKS

### ISSUE THREAD

**Issue by madz0** [google/bundletool#86] opened 2019-07-05 15:51 UTC
**Describe the bug**
Installing from apks to a connected device cause NPE

**Bundletool version(s) affected**
Version: 0.10.0

**Stacktrace**
```java
[BT:0.10.0] Error: null
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
	at com.google.common.base.Joiner.toString(Joiner.java:454)
	at com.google.common.base.Joiner.appendTo(Joiner.java:106)
	at com.google.common.base.Joiner.appendTo(Joiner.java:154)
	at com.google.common.base.Joiner.join(Joiner.java:197)
	at com.google.common.base.Joiner.join(Joiner.java:187)
	at com.google.common.base.Joiner.join(Joiner.java:205)
	at com.android.ddmlib.Device.installRemotePackage(Device.java:1024)
	at com.android.ddmlib.Device.installPackage(Device.java:902)
	at com.android.ddmlib.Device.installPackage(Device.java:880)
	at com.android.ddmlib.Device.installPackage(Device.java:869)
	at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:113)
	at com.android.tools.build.bundletool.device.ApksInstaller.installOnDevice(ApksInstaller.java:94)
	at com.android.tools.build.bundletool.device.ApksInstaller.installApks(ApksInstaller.java:82)
	at com.android.tools.build.bundletool.device.ApksInstaller.installApks(ApksInstaller.java:44)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:165)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:88)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
```

**To Reproduce**
1. Generate an `apks` from an existing bundle using the following command:
```
java -jar /absolute/path/to/bundletool-all-0.10.0.jar build-apks --bundle= /absolute/path/to/xxx.aab --output=/home/user/Desktop/xxx.apks --ks= /absolute/path/to/key.jks --ks-pass=file:/absolute/path/to/keystore.pwd --ks-key-alias=KeyAlias --key-pass=file:/absolute/path/to/key.pwd --overwrite
```
That generates `xxx.apks`

2. Issue the following command to install `apks` to the connected device:
```
java -jar /absolute/path/to/bundletool-all-0.10.0.jar install-apks --apks=/home/user/Desktop/xxx.apks
```

**Expected behavior**
Expected no exception. To generate and install the app to the connected device

**Known workaround**

**Environment:**
OS: Ubtuntu 14.04

**Additional context**

**Comment by plecesne** [comment] 2019-07-05 20:17
Dupe of #49.
Note that there is a workaround mentioned (use of the `--allow-downgrade` flag).

**Closed by plecesne** 2019-07-05 20:17 UTC
