### ISSUE TITLE
Unable to convert from AAB to apk

### ISSUE THREAD

**Issue by JimmyZeng2020** [google/bundletool#233] opened 2021-08-04 06:57 UTC
**Describe the bug**
Error: Unable to sign APK.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Unable to sign APK.

**Bundletool version(s) affected**
Version:1.7.1

**Stacktrace**
[BT:1.7.1] Error: Unable to sign APK.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Unable to sign APK.
        at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
        at com.android.tools.build.bundletool.io.ApkSigner.signApk(ApkSigner.java:109)
        at com.android.tools.build.bundletool.io.ApkzlibApkSerializerHelper.writeToZipFile(ApkzlibApkSerializerHelper.java:163)
        at com.android.tools.build.bundletool.io.ApkzlibApkSerializerHelper.writeToZipFile(ApkzlibApkSerializerHelper.java:107)
        at com.android.tools.build.bundletool.io.StandaloneApkSerializer.writeToDiskInternal(StandaloneApkSerializer.java:76)
        at com.android.tools.build.bundletool.io.StandaloneApkSerializer.writeToDisk(StandaloneApkSerializer.java:43)
        at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.addStandaloneApk(ApkSetBuilderFactory.java:130)
        at com.android.tools.build.bundletool.io.ApkSerializerManager$ApkSerializer.serialize(ApkSerializerManager.java:495)
        at com.android.tools.build.bundletool.io.ApkSerializerManager.lambda$null$4(ApkSerializerManager.java:233)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.FileAlreadyExistsException: C:\Users\ADMINI~1\AppData\Local\Temp\ApkSigner8692769618746037366\signed.apk -> C:\Users\ADMINI~1\AppData\Local\Temp\AutoValue_BuildApksCommand1406259994248899367\standalones\standalone-armeabi_v7a_xhdpi.apk
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
        at java.nio.file.Files.move(Unknown Source)
        at com.android.tools.build.bundletool.io.ApkSigner.signApk(ApkSigner.java:100)
        ... 13 more

**Expected behavior**
Apks generated successfully

**Known workaround**
Minsdkversion = 16 generated failure
Minsdkversion = 21 generated successfully

**Environment:**
OS: Win10

**Additional context**
Android studio 4.1.2

**Comment by ymakhno** [comment] 2021-08-05 09:20
Could you please share a sample project to reproduce this?

**Comment by JimmyZeng2020** [comment] 2021-08-06 07:07
New sample projects can be generated, but the old playstore project can't work.  On two computers,  one can be generated and the other can't. What factors will affect the generation?

**Comment by JimmyZeng2020** [comment] 2021-08-06 07:07
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

**Comment by JimmyZeng2020** [comment] 2021-08-06 07:07
------------------------------------------------------------
Gradle 6.6.1
------------------------------------------------------------

Build time:   2020-08-25 16:29:12 UTC
Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_202 (Oracle Corporation 25.202-b08)
OS:           Windows 10 10.0 amd64

**Comment by JimmyZeng2020** [comment] 2021-08-06 10:08
One step delay debugging will succeed
![image](https://user-images.githubusercontent.com/88423375/128494847-d5b4dea9-b6fb-4b23-a3d7-fbe8a7083da2.png)

**Comment by ymakhno** [comment] 2021-08-11 22:52
Unfortunately this issue doesn't contain enough information to identify the root cause. I'll close it for now, feel free to reopen if you have example project/steps to reproduce, so I can reproduce and investigate the issue.

**Closed by ymakhno** 2021-08-11 22:52 UTC
