### ISSUE TITLE
Error run android test for unremovable dynamic feature module

### ISSUE THREAD

**Issue by yeuristic** [google/bundletool#208] opened 2021-03-18 07:07 UTC
**Describe the bug**
Error when makeApk for android test in dynamic feature that configured as unremovable
`<dist:removable dist:value="false" />`

**Bundletool version(s) affected**
Version: 1.0.0

**Stacktrace**
com.android.tools.build.bundletool.model.exceptions.InvalidCommandException: The APK Set archive does not contain the following modules: [dynamicfeature]

**To Reproduce**
1. Create android project with a dynamic feature module
2. Set dynamic feature module delivery to install-time and removable value = false
3. Create an android test scenario for an activity in dynamic feature module
4. Run the test: `./gradlew dynamicfeature:connectedDebugAndroidTest`

or just checkout from [here](https://github.com/yeuristic/dfm-android-test)

**Expected behavior**
Android Test can be run successfully

**Known workaround**
Set dynamic feature module removable value to true. `<dist:removable dist:value="true" />`

**Environment:**
OS: macOS Mojave

**Additional context**
.

**Comment by ymakhno** [comment] 2021-03-30 10:23
Thank you for the sample project I was able to reproduce it.

This looks like Android Gradle Plugin issue, could you please report to them http://issuetracker.google.com/issues?q=componentid:192709.

**Comment by ymakhno** [comment] 2021-08-03 08:28
Fixed in 1.7.1

**Closed by ymakhno** 2021-08-03 08:28 UTC
