### ISSUE TITLE
APKs splitting removes METADATA files from googlei18n/libphonenumber

### ISSUE THREAD

**Issue by RSDosev** [google/bundletool#69] opened 2019-04-23 08:39 UTC
**Describe the bug**
The application I am currently working on is using the googlei18n/libphonenumber library. When generating the app.apks and installing the APK to the connected devices the application crashes because some METADATA files are missing from the googlei18n/libphonenumber library.

**Bundletool version(s) affected**
Version: 0.9.0

**Stacktrace**
```
'com.googlecode.libphonenumber:libphonenumber:7.7.2'. The missung resources are all the language format METADATA (PhoneNumberMetadataProto). :/

04-19 13:49:44.439 25369-25369/com.xxxxxxx.xxxxxxx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxxxxxx.xxxxxxx, PID: 25369
    java.lang.IllegalStateException: missing metadata: /com/google/i18n/phonenumbers/data/PhoneNumberMetadataProto_LT
        at com.google.i18n.phonenumbers.MultiFileMetadataSourceImpl.loadMetadataFromFile(MultiFileMetadataSourceImpl.java:117)
        at com.google.i18n.phonenumbers.MultiFileMetadataSourceImpl.getMetadataForRegion(MultiFileMetadataSourceImpl.java:72)
        at com.google.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegion(PhoneNumberUtil.java:2113)
        at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:2965)
        at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2829)
        at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2819)
        at net.rimoto.intlphoneinput.IntlPhoneInput.getPhoneNumber(IntlPhoneInput.java:344)
        at net.rimoto.intlphoneinput.IntlPhoneInput.isValid(IntlPhoneInput.java:367)
        at net.rimoto.intlphoneinput.IntlPhoneInput$1.onItemSelected(IntlPhoneInput.java:62)
        at android.widget.AdapterView.fireOnSelected(AdapterView.java:931)
        at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:920)
        at android.widget.AdapterView.-wrap1(AdapterView.java)
        at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:890)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5422)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**To Reproduce**
Just use the googlei18n/libphonenumber library in a sample app and try to run the bundletool on this app

**Comment by plecesne** [comment] 2019-04-23 13:33
Could not reproduce. 

I've added the `'com.googlecode.libphonenumber:libphonenumber:7.7.2'.` dependency, built a bundle, then build the APKs and the `com/google/i18n/phonenumbers/data/*` files are still present in the generated APKs.

**Comment by RSDosev** [comment] 2019-04-23 13:43
The exception is thrown when the meta files are accessed. :/

**Comment by plecesne** [comment] 2019-04-23 14:23
Works for me at runtime as well calling `PhoneNumberUtil.getInstance().parse("07000456123", "GB")`

You will need to provide a project sample that reproduces the bug.

**Comment by RSDosev** [comment] 2019-04-24 06:28
Unfortunatelly I can't send you the project I am working on, but one thing I forgot to tell you is that I am not using the `com.googlecode.libphonenumber:libphonenumber` directly. I am using this library -> [Here](https://github.com/AlmogBaku/IntlPhoneInput). The issue comes from it.

**Comment by plecesne** [comment] 2019-04-24 08:10
You don't need to share your project, the smallest sample project that reproduces the issue would actually be ideal. Without a way to reproduce the issue, it is impossible for us to help you find the root cause of your issue.

**Comment by plecesne** [comment] 2019-06-08 20:47
In the absence of response, I'll close this bug. Feel free to reopen if the issue persists and you're able to provide a sample that reproduces the issue.

**Closed by plecesne** 2019-06-08 20:47 UTC
