### ISSUE TITLE
bundletool build-bundle fails to find AndroidManifest.xml

### ISSUE THREAD

**Issue by justinpapezsonos** [google/bundletool#80] opened 2019-06-10 18:48 UTC
**Describe the bug**
According to the official "build your app from the command line" Android documentation, https://developer.android.com/studio/build/building-cmdline#package_pre-compiled_code_and_resources, one should be able to build an Android App Bundle from pre-compiled code and resources using `bundletool`. More specifically, one should be able to do this via `bundletool build-bundle`. When trying to build an Android App Bundle via `bundletool build-bundle --modules base.zip --output artifact.aab`, I am receiving the following error: `[BT:0.9.0] Error: Module 'base' is missing mandatory file 'manifest/AndroidManifest.xml'.` My pre-zipped folder structure is as follows:
```
.
|── ...
|── manifest
|   └── AndroidManifest.xml
└── ...
```

**Bundletool version(s) affected**
Version: 0.9.0

**Stacktrace** 
```
[BT:0.9.0] Error: Module 'base' is missing mandatory file 'manifest/AndroidManifest.xml'.
com.android.tools.build.bundletool.model.exceptions.BundleFileTypesException$MandatoryModuleFileMissingException: Module 'base' is missing mandatory file 'manifest/AndroidManifest.xml'.
	at com.android.tools.build.bundletool.validation.MandatoryFilesPresenceValidator.checkModuleHasAndroidManifest(MandatoryFilesPresenceValidator.java:80)
	at com.android.tools.build.bundletool.validation.MandatoryFilesPresenceValidator.validateModuleZipFile(MandatoryFilesPresenceValidator.java:41)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.lambda$validateModuleZipFile$2(ValidatorRunner.java:53)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at com.android.tools.build.bundletool.validation.ValidatorRunner.validateModuleZipFile(ValidatorRunner.java:53)
	at com.android.tools.build.bundletool.validation.BundleModulesValidator.validate(BundleModulesValidator.java:77)
	at com.android.tools.build.bundletool.commands.BuildBundleCommand.execute(BuildBundleCommand.java:195)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:70)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
```

**To Reproduce**
Create a new directory and name it `base`. Create a child directory within `base` and name it `manifest`. Place your `AndroidManifest.xml` file within the child `manifest` directory. Compress the `base` directory into a `.zip` file. Run the following command: `bundletool build-bundle --modules base.zip --output artifact.aab`.

**Expected behavior**
`bundletool build-bundle` does not throw a `[BT:0.9.0] Error: Module 'base' is missing mandatory file 'manifest/AndroidManifest.xml'.` Alternatively, if there truly is an error related to the `AndroidManifest.xml` file at play, an error is thrown that is indicative of the root issue.

**Known workaround**
None at this point in time.

**Environment:**
OS X 10.15.5

**Comment by plecesne** [comment] 2019-06-11 11:51
I just tried with a `base.zip` file containing just "manifest/AndroidManifest.xml" and it worked. If you can share a minimum sample that can reproduce the bug, I can look into it further.

**Comment by justinpapezsonos** [comment] 2019-06-11 19:23
Hey @plecesne, thanks for sharing the steps that you ran. When I run the steps you have provided, I am now able to successfully find the `AndroidManifest.xml` file via the `bundletool build-bundle` invocation. 

It seems as though the error I was seeing is caused by the way I was compressing the module directory. If still interested, here are more specific repro. steps for a Mac running OS X 10.15.5:
```
$ mkdir base
$ mkdir base/manifest
$ (...create manifest in proto format...)
$ (...in a Mac Finder window, right click on the "base" directory and select the "Compress "base"" option...)
$ bundletool build-bundle --modules base.zip --output bundle.aab
```

**Comment by plecesne** [comment] 2019-06-11 19:35
Great, thanks for closing the loop.

**Closed by plecesne** 2019-06-11 19:35 UTC

**Comment by justinpapezsonos** [comment] 2019-06-11 21:41
I think it is important that the official documentation, https://developer.android.com/studio/build/building-cmdline#build_your_app_bundle_using_bundletool,  is updated to specify that the way modules are compressed **does** matter. Based on the current documentation, this is not immediately apparent. I believe updating the documentation will help prevent other developers from running into similar issues.

On a side note, I think it may also be helpful for developers if the `bundletool build-bundle` command threw more specific errors. Throwing a `Module 'base' is missing mandatory file 'manifest/AndroidManifest.xml'` feels misleading and inaccurate, as the `base` module in the example I provided above does indeed contain a `manifest/AndroidManifest.xml` file in the protobuf format.

Thanks again for your help!

**Comment by plecesne** [comment] 2019-06-11 22:22
I believe the issue is not with the documentation. 

The documentation clearly states that bundletool expects a ZIP file, but the "Archive Utility" by MacOS does not create a ZIP file by default, it uses a different format. It looks like you can [configure it to use a zip file](https://www.macobserver.com/tmo/article/how-to-use-and-customize-os-xs-built-in-archive-utility-app) though if you need.

**Comment by justinpapezsonos** [comment] 2019-06-11 22:29
Ah, great information, and an oversight on my part. Thanks!

**Comment by gapinthetraffic** [comment] 2019-08-30 10:32
Hi, I saw your code fix (see below). But surely this code just bundles the Manifest file on its own? How can I get my com.ASDating.android.apk to bundle when it still says  "missing mandatory file 'manifest/AndroidManifest.xml'."?

$ mkdir base
$ mkdir base/manifest
$ (...create manifest in proto format...)
$ (...in a Mac Finder window, right click on the "base" directory and select the "Compress "base"" option...)
$ bundletool build-bundle --modules base.zip --output bundle.aab

**Comment by plecesne** [comment] 2019-09-02 17:20
As explained in my comment above, clicking "Compress base" in Mac does not create a ZIP file. I event provided a link on how to fix it.

**Comment by elbosp** [comment] 2022-01-15 14:30
You should first create AndroidManifest proto using aapt. Check this tutorial [https://musteresel.github.io/posts/2019/07/build-android-app-bundle-on-command-line.html](url)
