### ISSUE TITLE
Bundle error when using services to load dynamic feature modules

### ISSUE THREAD

**Issue by rfha** [google/bundletool#142] opened 2020-01-30 02:39 UTC
**Describe the bug**
When using ServiceLoaders to load dynamic feature modules, bundle tool throws an error if there are implementations of the same service interface within different modules.

**Bundletool version(s) affected**
Version: 0.12.0

**Stacktrace**
`Execution failed for task ':app:packageReleaseBundle'.`
`A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade`
` Modules 'base' and 'other' contain entry 'root/META-INF/services/com.package.ServiceImplementation' with different content.`

**To Reproduce**
Create a project with one base and one dynamic feature module.
Add a service interface and an implementation for this service in each module.
Annotate the services with the google AutoService or add the service definitions manually to META-INF/services.
Now try to build an app bundle.

**Expected behavior**
The expected behaviour would be that each split apk would have the service definition for the corresponding service implementation in that module and the app bundle would build without any errors.

**Known workaround**
I have not found any good workarounds yet.
As for now I define all service implementations in all modules and check if the implementations listed actually exist.
Maybe it would be possible to exclude the service definitions from the comparison done here:

https://github.com/google/bundletool/blob/1c41e70de5f635ceb39c264204de10562b320318/src/main/java/com/android/tools/build/bundletool/validation/EntryClashValidator.java#L58-L68

**Environment:**
OS: Mac OS Catalina as well as the docker image jangrewe/gitlab-ci-android in the newest version

**Comment by plecesne** [comment] 2020-01-30 10:20
When all the modules are installed on the device, all the files appear as a single APK to the Android platform, so when your app will try to read this file, the platform will arbitrarily load one file but you won't be able to predict which one. This is why we have this check in place.

**Comment by rfha** [comment] 2020-01-30 23:28
Thanks for the fast response.

Would it make sense to add the option to define that specific files should be merged when building the app bundle? For example:

```groovy
android{
    bundle{
        packagingOptions {
            merge 'root/META-INF/services/com.package.MyService'
            }
        }
    }
}
```

**Comment by plecesne** [comment] 2020-01-30 23:34
Do you pull these files from a third party library or SDK? Or where do these files come from? Could you simply exclude one of them from one of the library instead if you don't need it?

**Comment by rfha** [comment] 2020-01-30 23:43
What I am trying to do is build dynamic feature modules that behave similar to java plugins loaded with the ServiceLoader class.
The idea is that the base module does not have to know each module but just call the ServiceLoader on each module.
For convenience I use the [Google AutoService annotation](https://github.com/google/auto/tree/master/service) so I don't have to create the META-INF/services files manually.
What I am doing at the moment to fix this error is compiling all modules, then merging the files with a short gradle script and then building the bundle. The problem is that I now can't use the ServiceProvider class because it fails if a class specified in the service definition does not exist. Because of that I also implemented a custom ServiceLoader that checks if the class exists before loading it.

**Comment by keyboardsurfer** [comment] 2020-01-31 09:45
It looks like you're creating two implementations with the same FQCN for an interface.
In which case the compiler is correct to throw an error.
What's your reason for not using a different classpath for these?

**Comment by rfha** [comment] 2020-01-31 09:51
The file in META-INF/services is not named after the FQCN of the implementation but the FQCN of the Interface. The error is not thrown by the compiler but bundle tool.

**Comment by keyboardsurfer** [comment] 2020-01-31 10:16
Now I'm with you on this. Yes, it looks like `merge` should be able to do the trick here.

**Comment by jeppeman** [comment] 2020-06-11 15:16
I had a similar error: `Modules 'base' and 'tap_on_phone_dynamic_feature' contain entry 'root/META-INF/services/io.jsonwebtoken.io.Deserializer' with different content.` 
The service in the error is registered through the `io.jsonwebtoken:jjwt-orgjon:0.11.0` artifact, which I in turn depend on only from my dynamic feature.

In my case the cause of this was when the base app module had a build type with minification (R8 enabled) that was not present in the dynamic feature module. i.e:
```gradle
android {
    buildTypes {
        instrumentation {
            initWith debug
            minifyEnabled true
            matchingFallbacks = ['debug']
        }
    }
}
```
With `minifyEnabled false` this works fine - R8 seems to make some packaging errors with this setup which caused the service to be registered both in the base module and the dynamic feature module.

In order to fix it I had to add the following to `build.gradle` of the dynamic feature module:
```gradle
android {
    buildTypes {
        instrumentation {
            initWith debug
            matchingFallbacks = ['debug']
        }
    }
}
```

**Comment by ymakhno** [comment] 2020-11-24 19:24
Closing as no bundletool issue here, bundletool should not allow files with the same name but different content because as described all the files appear as a single APK to the Android platform. 

The proposed solution, merging of provider-configuration files, can not be implemented in bundletool and relates to Android Gradle Plugin. Please create an issue in their issue tracker https://issuetracker.google.com/issues?q=componentid:192709 to get proper attention if this is still relevant. But even if implemented developers would still have to ensure that some implementation may be not available because they relate to on-demand features that are not installed on a device.

**Closed by ymakhno** 2020-11-24 19:24 UTC

**Comment by mtotschnig** [comment] 2025-01-22 07:35
The difference in behavior might be due to AGP 8.7.3 depending on Bundletool 1.17.1, while 8.8.0 depends on 1.17.2.

**Comment by mtotschnig** [comment] 2025-03-08 13:42
I reported this also as https://issuetracker.google.com/issues/401693549 where I documented a solution.
