### ISSUE TITLE
<dist:fusing dist:include="false"/> is not working properly.

### ISSUE THREAD

**Issue by ganadist** [google/bundletool#141] opened 2020-01-28 06:39 UTC
**Describe the bug**

On https://developer.android.com/studio/command-line/bundletool#generate_apks, document describes `bundletool includes only dynamic feature modules that specify <dist:fusing dist:include="true"/> in their manifest in a universal APK.`
But, it includes all dynamic features even if `<dist:fusing dist:include="false"/>` is set.

**Bundletool version(s) affected**
Version: 0.10.3 (bundled on AGP 3.5.3)

**Stacktrace**
N/A

**To Reproduce**
```
$ git clone https://github.com/ganadist/VersionCodeDemo
$ cd VersionCodeDemo
$ ./gradlew :app:packageDebugUniversalApk
$ aapt d --values xmltree  app/build/outputs/universal_apk/debug/app-debug-universal.apk AndroidManifest.xml |grep -A 1 activity
      E: activity (line=20)
        A: android:name(0x01010003)="com.example.myapplication.MainActivity" (Raw: "com.example.myapplication.MainActivity")
--
      E: activity (line=27)
        A: android:name(0x01010003)="com.example.dynamicfeature1.TestActivity" (Raw: "com.example.dynamicfeature1.TestActivity")
```

**Expected behavior**
```
$ aapt d --values xmltree  app/build/outputs/universal_apk/debug/app-debug-universal.apk AndroidManifest.xml | grep -A 1 activity
      E: activity (line=20)
        A: android:name(0x01010003)="com.example.myapplication.MainActivity" (Raw: "com.example.myapplication.MainActivity")
```

**Known workaround**
If you have found a workaround, please specify what it is.

**Environment:**
N/A

**Additional context**
Fusing option is set as `false` at https://github.com/ganadist/VersionCodeDemo/blob/master/dynamicfeature1/src/main/AndroidManifest.xml#L13
But com.example.dynamicfeature1.TestActivity is included at universal apk

**Comment by plecesne** [comment] 2020-01-28 16:16
This is working as intended.
The definition of the activities are still merged in the AndroidManifest.xml of the base, however the dex files, resources, assets and native libraries are not.

**Closed** 2020-04-23 13:47 UTC
