### ISSUE TITLE
Bundletool not using keystore provided by --ks flag

### ISSUE THREAD

**Issue by tir38** [google/bundletool#115] opened 2019-08-20 19:10 UTC
**Describe the bug**
We use bundletool in a script:

```
#!/usr/bin/env bash

...

bundleLocation="app/build/outputs/bundle/release/app-release.aab"

output="my-apks"
apksLocation="${output}.apks"
java -jar ${jarFile} build-apks \
--bundle=${bundleLocation} \
--output=${apksLocation} \
--overwrite	\
--mode=universal \
--ks=dev_resources/MyReleaseKeystore.keystore \
--ks-key-alias="REDACTED" \
--ks-pass=pass:"REDACTED"  \
--key-pass=pass:"REDACTED"
```

We also have inside our app's build.gradle file:

```
android {
   // env vars set by C.I. server
    def releaseKeystoreLocation = "../dev_resources/" + System.getenv("KEYSTORE_NAME")
    signingConfigs {
        release {
            storeFile file(releaseKeystoreLocation)
            storePassword System.getenv("KEYSTORE_PASSWORD")
            keyAlias  System.getenv("KEY_ALISAS")
            keyPassword System.getenv("KEY_PASSWORD")
        }
...
}
```

I was under the impression that these signing configs in build.gradle were NOT used by bundletool (hence the reason we used the `--ks`, `--ks_*`, etc flags)

When we run our script we get this error:

```
Execution failed for task ':app:validateSigningRelease'.
> Keystore file '/Users/example/ourproject/dev_resources/null' not found for signing config 'release'.
```
This is obviously happening cause the script is using signing configs in build.gradle and we have not set the env vars locally. Why is bundletool using signing configs? Why is it not using the  keystore supplied via `--ks=dev_resources/MyReleaseKeystore.keystore` ?

**Bundletool version(s) affected**
Version: 0.10.2

**Expected behavior**
I would expect bundletool to use the keystore provided by `--ks` flag

**Environment:**
OS: macOS 10.13.6 (17G7024)

**Comment by tir38** [comment] 2019-08-20 19:28
Actually maybe I don't understand the reason for the `--ks`, `--ks-key-alias` etc flags. If I manually set the keystore path env var then the next thing bundletool complains about is a non-set `storePassword` . So I suppose I have to set all the signing vars inside build.gradle. Then what is the point of the `--ks` etc flags?

**Comment by plecesne** [comment] 2019-08-21 13:29
```
Execution failed for task ':app:validateSigningRelease'.
```
is an error produced by Gradle, not bundletool. In other words, the issue is not related to the execution of bundletool but of your `validateSigningRelease` task which seems to be using Gradle signing configuration.

**Comment by plecesne** [comment] 2019-09-17 14:28
Closing for lack of update. Also, the error suggests this is not a bundletool issue.

**Closed by plecesne** 2019-09-17 14:28 UTC
