### ISSUE TITLE
Bundletool "install-apks" command only install base.apk

### ISSUE THREAD

**Issue by JingYeoh** [google/bundletool#98] opened 2019-07-25 08:09 UTC
**Describe the bug**
Bundletool `install-apks` command only install base.apk，but i use `extract-apks` command with same device-spec and i got two apks（base-master.apk、base-arm64_v8a.apk）,
and this error is just happened in Android phone: OPPO R11 plus for now

**Bundletool version(s) affected**
Version: 0.10.0

**Environment:**
Android phone: OPPO R11 plus

**device spec**
```json
{
  "supportedAbis": ["arm64-v8a", "armeabi-v7a", "armeabi"],
  "supportedLocales": ["zh-TW"],
  "deviceFeatures": ["reqGlEsVersion=0x30002", "android.hardware.audio.output", "android.hardware.bluetooth", "android.hardware.bluetooth_le", "android.hardware.camera", "android.hardware.camera.any", "android.hardware.camera.autofocus", "android.hardware.camera.flash", "android.hardware.camera.front", "android.hardware.faketouch", "android.hardware.fingerprint", "android.hardware.location", "android.hardware.location.gps", "android.hardware.location.network", "android.hardware.microphone", "android.hardware.opengles.aep", "android.hardware.screen.landscape", "android.hardware.screen.portrait", "android.hardware.sensor.accelerometer", "android.hardware.sensor.compass", "android.hardware.sensor.gyroscope", "android.hardware.sensor.light", "android.hardware.sensor.proximity", "android.hardware.sensor.stepcounter", "android.hardware.sensor.stepdetector", "android.hardware.telephony", "android.hardware.telephony.cdma", "android.hardware.telephony.gsm", "android.hardware.touchscreen", "android.hardware.touchscreen.multitouch", "android.hardware.touchscreen.multitouch.distinct", "android.hardware.touchscreen.multitouch.jazzhand", "android.hardware.usb.accessory", "android.hardware.usb.host", "android.hardware.vulkan.level", "android.hardware.vulkan.version=4194307", "android.hardware.wifi", "android.hardware.wifi.direct", "android.software.app_widgets", "android.software.backup", "android.software.connectionservice", "android.software.device_admin", "android.software.home_screen", "android.software.input_methods", "android.software.live_wallpaper", "android.software.midi", "android.software.print", "android.software.sip", "android.software.sip.voip", "android.software.voice_recognizers", "android.software.webview", "oppo.Align.alarm.support", "oppo.all.client", "oppo.all.client_7_5", "oppo.ams.act.freqcontrol", "oppo.ams.broadcast.adjust.obrecque", "oppo.ams.broadcast.adjust.pbrecque", "oppo.ams.broadcast.filter.power", "oppo.ams.broadcast.jumpqueue", "oppo.ams.broadcast.oppobt", "oppo.app2sd.disabled", "oppo.autobrightctl.animation.support", "oppo.battery.notify.new", "oppo.black.gesture.proximitysensor.support", "oppo.black.gesture.wake.up.arouse.support", "oppo.breath.light.support", "oppo.brightness.mode.automatic", "oppo.button.light.support", "oppo.cdma.mixed.volte.support", "oppo.charge.sound.noplay", "oppo.childspace.support", "oppo.color.temperature.adjustment.not.support", "oppo.coloros.fake.bs", "oppo.commcenter.reboot.dialog", "oppo.common_center.wlan.assistant", "oppo.dirac.support", "oppo.disable.small.window.leather", "oppo.eyeprotect.support", "oppo.feature.16103", "oppo.filtrated.app", "oppo.fingerprint.sensor.front", "oppo.fingerprint.support", "oppo.front.touch.fingerprint.sensor", "oppo.front.touch.fingerprint.tpprotect", "oppo.fulldiskencryption.unsupported", "oppo.gallery.opencabc", "oppo.guard.elf.support", "oppo.hardware.face.support", "oppo.hw.manufacturer.qualcomm", "oppo.inexact.alarm", "oppo.jobscheduler.support", "oppo.launcher.download.progress.support", "oppo.launcher.layout5x4", "oppo.lcd.first.tp.last.support", "oppo.memory.auto.clean", "oppo.memory.auto.deep.clean", "oppo.multiapp.support", "oppo.multibits.dimming.support", "oppo.multimedia.record.conflict", "oppo.null.rom", "oppo.null.rom.allnet", "oppo.ocloud.photo.sync", "oppo.ota.reserve.support", "oppo.otg.connection.menu.support", "oppo.outdoor.brightness.support", "oppo.package.encrypt.support.only", "oppo.performance.power.netwake", "oppo.qualcomm.gemini.support", "oppo.screen.hovering.support", "oppo.securitypay.support", "oppo.selfprotect.support", "oppo.sensor.dynamic.calibrate", "oppo.softsim.ignore_data_setting", "oppo.soundeffect.support", "oppo.support.single.partition", "oppo.sw.solution.device", "oppo.sw.solution.rom", "oppo.tp.limit.support", "oppo.volte.support"],
  "screenDensity": 480,
  "sdkVersion": 25
}
```

![image](https://user-images.githubusercontent.com/20204119/61857009-e09b3780-aef5-11e9-81d4-d120eb53816c.png)

**Comment by plecesne** [comment] 2019-07-25 15:52
Can you try this command instead to see the installed APKs?
```
adb shell dumpsys package com.ss.android.ugc.trill | grep split
```

**Comment by JingYeoh** [comment] 2019-07-29 13:12
> Can you try this command instead to see the installed APKs?
> 
> ```
> adb shell dumpsys package com.ss.android.ugc.trill | grep split
> ```

sorry for replay late, this command result is still only one apk(base.apk).
but this is just happened on device `OPPO R11 plus` and installed by bundletool, we installed apk by upload aab to GP Internal sharing test，and got two apks.

**Comment by bing2006200** [comment] 2019-08-30 08:05
hi, 想问下，这个问题你那边解决了麽？
我也遇到了相同的问题，在oppo, vivo, sumsung手机上都有出现。

**Comment by tcking** [comment] 2019-10-03 15:32
same issue on OPPO R15,only install base.apk and crashed when start app because of can't find some resource

**Comment by plecesne** [comment] 2019-10-03 16:50
Could you please share the `device-spec.json` file generated for one of these devices by the command `bundletool get-device-spec`?

```
java -jar bundletool-all.jar get-device-spec --output=/tmp/device-spec.json
```

**Comment by bing2006200** [comment] 2019-10-09 08:02
java -jar bundletool-all.jar get-device-spec --output=/tmp/device-spec.json

Results:::
{
  "supportedAbis": ["arm64-v8a", "armeabi-v7a", "armeabi"],
  "supportedLocales": ["zh-CN"],
  "deviceFeatures": ["reqGlEsVersion=0x30002", "android.hardware.audio.output", "android.hardware.bluetooth", "android.hardware.bluetooth_le", "android.hardware.camera", "android.hardware.camera.any", "android.hardware.camera.autofocus", "android.hardware.camera.flash", "android.hardware.camera.front", "android.hardware.faketouch", "android.hardware.fingerprint", "android.hardware.location", "android.hardware.location.gps", "android.hardware.location.network", "android.hardware.microphone", "android.hardware.opengles.aep", "android.hardware.ram.normal", "android.hardware.screen.landscape", "android.hardware.screen.portrait", "android.hardware.sensor.accelerometer", "android.hardware.sensor.compass", "android.hardware.sensor.gyroscope", "android.hardware.sensor.light", "android.hardware.sensor.proximity", "android.hardware.sensor.stepcounter", "android.hardware.sensor.stepdetector", "android.hardware.telephony", "android.hardware.telephony.cdma", "android.hardware.telephony.gsm", "android.hardware.touchscreen", "android.hardware.touchscreen.multitouch", "android.hardware.touchscreen.multitouch.distinct", "android.hardware.touchscreen.multitouch.jazzhand", "android.hardware.usb.accessory", "android.hardware.usb.host", "android.hardware.vulkan.compute", "android.hardware.vulkan.level", "android.hardware.vulkan.version=4194307", "android.hardware.wifi", "android.hardware.wifi.direct", "android.software.activities_on_secondary_displays", "android.software.app_widgets", "android.software.autofill", "android.software.backup", "android.software.companion_device_setup", "android.software.connectionservice", "android.software.cts", "android.software.device_admin", "android.software.home_screen", "android.software.input_methods", "android.software.live_wallpaper", "android.software.managed_users", "android.software.midi", "android.software.picture_in_picture", "android.software.print", "android.software.sip", "android.software.sip.voip", "android.software.voice_recognizers", "android.software.webview"],
  "screenDensity": 480,
  "sdkVersion": 27
}

**Comment by EthanMin** [comment] 2019-11-25 09:29
My app 

> > Can you try this command instead to see the installed APKs?
> > ```
> > adb shell dumpsys package com.ss.android.ugc.trill | grep split
> > ```
> 
> sorry for replay late, this command result is still only one apk(base.apk).
> but this is just happened on device `OPPO R11 plus` and installed by bundletool, we installed apk by upload aab to GP Internal sharing test，and got two apks.

My app also only one apk in some devices installed by GP.

**Comment by ymakhno** [comment] 2020-11-20 20:26
This should be fixed in bundletool 1.4.0.

**Closed by ymakhno** 2020-11-20 20:26 UTC

**Comment by JWXjwx** [comment] 2020-12-02 08:58
This bug still exist in bundletool 1.4.0.

**Comment by ymakhno** [comment] 2020-12-02 14:04
I can't reproduce this issue anymore. If there is a sample project available to reproduce this I would be happy to investigate further.

**Comment by dechaow** [comment] 2021-03-02 03:42
This bug still exist in bundletool 1.5.0.

Environment:
Android phone: OPPO R11

**Comment by zwy440** [comment] 2021-06-02 05:42
Oppo a3 has the same bug. 
![image](https://user-images.githubusercontent.com/4748260/120429658-5bfa8980-c3a8-11eb-8d5a-70ed400cd8b1.png)
only one apk

**Comment by zwy440** [comment] 2021-06-02 05:58
I have the latest progress，if I set abi enableSplit = fasle，it’s ok。The app run ok。
![image](https://user-images.githubusercontent.com/4748260/120431008-77669400-c3aa-11eb-8f83-d0c9418e4d00.png)
The folder lib has arm64 and arm64 has my so files.

**Comment by RaulLpg** [comment] 2022-11-29 03:06
Experiencing the same issue with Oppo A5
